services:
  # Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://api-gateway:4000
    depends_on:
      - api-gateway

  # API Gateway
  api-gateway:
    build:
      context: ./server/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./server/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - AUTH_SERVICE_URL=http://auth-service:4001
      - ML_SERVICE_URL=http://ml-service:4002
      - ANALYTICS_SERVICE_URL=http://analytics-service:4003
    depends_on:
      - auth-service
      - ml-service
      - redis

  # Auth Service
  auth-service:
    build:
      context: ./server/auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "4001:4001"
    volumes:
      - ./server/auth-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=healthcare
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  # ML Service
  ml-service:
    build:
      context: ./server/ml-service
      dockerfile: Dockerfile.dev
    ports:
      - "4002:4002"
    volumes:
      - ./server/ml-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - JWT_SECRET_KEY=your-secret-key-for-development
      - AUTH_SERVICE_URL=http://auth-service:4001
    depends_on:
      - auth-service

  #Analytics Service
  timescaledb-analytics:  # Changed name to avoid conflict
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5434:5432"  # Changed port to avoid conflict with existing TimescaleDB
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=healthcare_analytics
    volumes:
      - timescaledb_analytics_data:/var/lib/postgresql/data

  analytics-service:
    build:
      context: ./server/analytics-service
      dockerfile: Dockerfile.dev
    ports:
      - "4003:4003"
    volumes:
      - ./server/analytics-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=timescaledb-analytics
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=healthcare_analytics
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:4001
    depends_on:
      - timescaledb-analytics
      - redis
      - auth-service

  # Databases
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=healthcare
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  timescaledb_analytics_data:

