global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']
  
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:4002']
